version: '3.8'
services:
  app:
    container_name: event-service
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=test
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
